# insert_logging.sh
# Add a python import statement and a call to logger.log_file() at the top of
# each python file in this directory.

for file in `ls *.py`
do
    basename=${file%.py}
    comment="# Adding logging to ncp-dev for this script.  This is automatically generated by insert_logging.sh\n"
    import="import logger\nlogger.log_model('$basename')\n"

    echo -e $comment$import | cat - $file > /tmp/out
    mv /tmp/out $file
done
