# Adding logging to ncp-dev for this script. This is automatically generated by insert_logging.sh
import logger
logger.log_model('profiler')

import pstats

if __name__ == "__main__":
    import sys
    p = pstats.Stats(sys.argv[1])
    p.strip_dirs().sort_stats('cumulative').print_stats()
